const fs = require('fs');

function parsePackage(filename, packageName) {
    const content = fs.readFileSync(filename, 'utf-8');
    const lines = content.split('\n').map(l => l.trim()).filter(l => l);

    const questionsMap = {};
    const answersMap = {};

    let currentQ = null;

    let parsingAnswers = false;

    for (const line of lines) {
        if (line.match(/^KUNCI JAWABAN/i)) {
            parsingAnswers = true;
            continue;
        }

        if (parsingAnswers) {
            const ansMatch = line.match(/^(\d+)\.\s*([A-E])/i);
            if (ansMatch) {
                const qNum = parseInt(ansMatch[1]);
                const ansChar = ansMatch[2].toUpperCase();
                answersMap[qNum] = ansChar.charCodeAt(0) - 65; // A=0, B=1, etc.
            }
        } else {
            const qMatch = line.match(/^(\d+)\.\s+\[(.*?)\]\s+(.*)/);
            if (qMatch) {
                currentQ = {
                    num: parseInt(qMatch[1]),
                    cat: qMatch[2].trim(),
                    q: qMatch[3].trim(),
                    opts: []
                };
                questionsMap[currentQ.num] = currentQ;
            } else if (currentQ) {
                const optMatch = line.match(/^[A-E]\.\s+(.*)/);
                if (optMatch) {
                    currentQ.opts.push(optMatch[1].trim());
                }
            }
        }
    }

    const finalQuestions = [];
    for (let i = 1; i <= 100; i++) {
        const q = questionsMap[i];
        if (!q) continue;
        const ans = answersMap[i];
        
        finalQuestions.push({
            category: q.cat,
            text: q.q,
            options: q.opts,
            correctAnswer: ans !== undefined ? ans : 0,
            explanation: `Kunci Jawaban: ${q.opts[ans !== undefined ? ans : 0]}`
        });
    }

    return {
        name: packageName,
        questions: finalQuestions
    };
}

const pkgA = parsePackage('../paket_a.txt', 'Paket A');
const pkgB = parsePackage('../paket_b.txt', 'Paket B');
const pkgC = parsePackage('../paket_c.txt', 'Paket C');

console.log(`Paket A: ${pkgA.questions.length} questions`);
console.log(`Paket B: ${pkgB.questions.length} questions`);
console.log(`Paket C: ${pkgC.questions.length} questions`);

// Read data.js and append the new packages
let dataJsContent = fs.readFileSync('data.js', 'utf-8');

// The easiest way is to evaluate data.js, modify examData, and then rewrite data.js
// But stringifying functions is tricky. Wait, the packages in data.js are generated by getUPKPQuestions().
// data.js has:
// examData = { upkp: { packages: [ { name: "Paket 1", questions: getUPKPQuestions() } ] }, ... }

// Instead of rewriting the whole file, we can append code to push these new packages into examData.upkp.packages
// at the end of data.js!

const appendCode = `
// Append new packages dynamically
const pkgA = ${JSON.stringify(pkgA, null, 4)};
const pkgB = ${JSON.stringify(pkgB, null, 4)};
const pkgC = ${JSON.stringify(pkgC, null, 4)};

if (typeof examData !== 'undefined' && examData.upkp && examData.upkp.packages) {
    examData.upkp.packages.push(pkgA);
    examData.upkp.packages.push(pkgB);
    examData.upkp.packages.push(pkgC);
}
`;

fs.appendFileSync('data.js', appendCode);
console.log("Successfully appended new packages to data.js");

